In [2]:
# Create a NumPy ndarray Object 
# NumPy is used to work with arrays. The array object in NumPy is called ndarray.
# To create an ndarray, we can pass a list, tuple or any array-like object i

In [5]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
# Dimensions in Arrays

In [10]:
# Create a 0-D array with value 42
# 0 dimension
arr = np.array(42)

print(arr)
print(arr.shape)

42
()


In [13]:
# 1-D Arrays

arr= np.array([1,2,3,4,5])
print(arr)
print(arr.shape)

[1 2 3 4 5]
(5,)


In [15]:
# 2-D Arrays

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [26]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
#  ndim attribute that returns an integer that tells us how many dimensions the array have.

In [25]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [33]:
# NumPy Array Indexing

arr = np.array([1, 2, 3, 4])
print(arr)
print(arr.ndim)
print(arr[0])
print(arr[1])
print(arr[0] + arr[1])

[1 2 3 4]
1
1
2
3


In [34]:
# NumPy Array Slicing

arr = np.array([1, 2, 3, 4, 5, 6, 7]) 
arr

array([1, 2, 3, 4, 5, 6, 7])

In [35]:
arr[1:5]

array([2, 3, 4, 5])

# Data Types 
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )


In [36]:
arr = np.array([1, 2, 3, 4])
arr.dtype

dtype('int32')

In [37]:
arr = np.array(['apple', 'banana', 'cherry'])
arr.dtype

dtype('<U6')

In [39]:
# The Difference Between Copy and View

# copy is a new array, and the view is just a view of the original array.

# The copy owns mthe data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

# The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view

In [40]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [42]:
copy = arr.copy()
copy

array([1, 2, 3, 4, 5])

In [43]:
arr[0] = 1000

In [44]:
print(arr)
print(copy)

[1000    2    3    4    5]
[1 2 3 4 5]


In [49]:
arr = np.array([1, 2, 3, 4, 5])
view = arr.view()


In [50]:
arr[0] = 42

In [51]:
print(arr)
print(view)

[42  2  3  4  5]
[42  2  3  4  5]


In [52]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 30000


In [53]:
print(arr)
print(x)

[30000     2     3     4     5]
[30000     2     3     4     5]


In [54]:
# Get the Shape of an Array

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [55]:
arr.shape

(2, 4)

In [56]:
#  () 안의 2,4 즉 2개가 있으니까 2 dimension 
# first dimension 는 2개의 elements , second dimension 는 4개의 elements 


In [58]:
arr = np.array([1, 2, 3, 4], ndmin=5)
arr

array([[[[[1, 2, 3, 4]]]]])

In [59]:
arr.shape 
# () 안에 1,1,1,1,4 즉, 숫자 5개가 있으니까  5차원. 
# 1-D 는 1개의 element, 2-D는 1개의 element, 3-D는 1개의 element ,..4-D는 1element, 5-D는 4elements

(1, 1, 1, 1, 4)

In [ ]:
# NumPy Array Reshaping

In [61]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [66]:
new = arr.reshape(4,3)  
new  # ()안의 숫자가 2개 있으니 2차원, 그리고 1-D는 4개의 elements, 2-D는 3개의 elements 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [65]:
new.ndim  # 2차원 

2

In [68]:
# Reshape From 1-D to 3-D

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2,3,2)
newarr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [70]:
newarr.shape

(2, 3, 2)

# Numpy 배열에 축 추가하기 

##  np.newaxis

In [71]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [72]:
arr.shape

(4,)

In [74]:
arr.ndim

1

In [79]:
# ':'를 사용해서 기존 배열의 값을 indexing
# np.newaxis attribute를 사용해서 길이가 1인 새로운 축

new = arr[:,np.newaxis]
print(new)
print(new.shape)
print(new.ndim)

[[1]
 [2]
 [3]
 [4]]
(4, 1)
2


In [87]:
new2 = arr[np.newaxis,:]
print(new2)
print(new2.shape)
print(new2.ndim)

[[1 2 3 4]]
(1, 4)
2


# shape(3, 4) 인 2차원의 배열에 길이가 1인 새로운 축을 추가해서 3차원 배열을 만들어보겠으! 


In [84]:
new2 = np.arange(12).reshape(3,4)
print(new2)
print(new2.shape)
print(new2.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2


In [89]:
new3 = new2[:,:,np.newaxis]
print(new3)
print(new3.shape)
print(new3.ndim)

[[[1]
  [2]
  [3]
  [4]]]
(1, 4, 1)
3


In [91]:
new3 = new2[:,np.newaxis,:]
print(new3)
print(new3.shape)
print(new3.ndim)

[[[1 2 3 4]]]
(1, 1, 4)
3


# numpy.linspace() 

- returns number spaces evenly w.r.t interval.

- numpy.linspace(start,stop, num, endpoint, dtype)

- start, stop은 required 나머지는 optional 

- num.default >> 50 
               


In [96]:
np.linspace(start = 1, stop = 3, num = 10)

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])