In [1]:
# iris  ( 붓꽃 ) 

# classfication (붗꽃 종류)

from sklearn import svm, metrics
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris 
import numpy as np 
import pandas as pd 

irisData = load_iris()
irisData.keys()


dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [2]:
irisData["DESCR"][:200] 

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive'

In [3]:
irisData["target_names"]

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [4]:
irisData["feature_names"]

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [5]:
irisData["data"]   # feature_names 의 데이터.

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
irisData["data"].shape  # 150개의 iris꽃의 4가지 특성

(150, 4)

In [7]:
irisData["data"][:10] # 10개 가져오기 

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [8]:
irisData["target"]   #0, 1, 2는 각각의 종류

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
## 훈련data와 test data 를 나뉘자  ( 75, 25)
##  using train - test split 
##  x 는 data로, y는 label를 뜻한다 

 


In [10]:
# scikit_learn 의 붓꽃 데이터 셋을 가져오기 

from sklearn.datasets import load_iris
irisData = load_iris()

# load_iris() 함수가 리턴하는 객체는 Bunch 클래스 객체
# Bunch 클래스 객체는 파이썬의 dictionary 와 유사한객체로
# 키와값으로 구성되어 있다

# 훈련데이터와 테스트데이터를 나누기위한함수
# train_test_split 모듈에 있는  train_test_split()
# train_test_split 모듈은 sklearn.jodel_selection 

from sklearn.model_selection import train_test_split

# scikit-learn  에서 데이터는 대문자 X로 표시하고 레이블은 소문자 y로 표시한다 

X_train, X_test, y_train, y_test = train_test_split( 
    irisData["data"], irisData["target"],random_state=0)   # random_state는 유사난소 생성기 


# train_test_split()의 리턴 타입은 모두 numpy 배열 





In [11]:
X_train.shape   # 75 프로의 훈련 데이터 

(112, 4)

In [12]:
X_test.shape   # 25프로의 테스트 데이터

(38, 4)

In [13]:
y_train.shape

(112,)

In [14]:
y_test.shape

(38,)

In [15]:
## KNN (K Nearest Neighbors )  >> 분류 머신 중 하나 >> 새로운 데이터의 가장 가까운 k개의 이웃을찾는다. 
## KNN 을사용하기 위해서는 neighbors 모듈에 KNeighborsClassifer 함수를 사용한다 
## KNeighborsClassfier() 함수에 중에 중요한 매개 변수는 n_neighbors >> 이 매개 변수는 이웃의 갯수를 지정하는 매개변수 

from sklearn.neighbors import KNeighborsClassifier 
knn = KNeighborsClassifier(n_neighbors=1)

# 모델을 만들기 위해서는 fit 메서드 사용 
# fit메서드의 리턴값은 knn객체를 리턴한다 

knn.fit(X_train, y_train)  #

KNeighborsClassifier(n_neighbors=1)

In [16]:
# 채집한 iris의 새로운 데이터(sample)이라고 가정하고 Numpy 배열로 특성값을 만든다
# sckitit-learn 에서는 항상 데이터가 2차원 배열(대문자) 일 것으로 예측/ 소문자는 vector

In [17]:
X_Newdata = np.array([[5.1,2.9, 1,0.3]])
X_Newdata.shape  # 종류가 1나인 (4개의 꽃특성, petal,sepal width 길이)

(1, 4)

In [18]:
# knn객체의 predict() 메서드를 사용하여 예측할 수 있다
prediction = knn.predict(X_Newdata)
prediction   # 새로운 데이터, X 는 품종이 0 (Setosa) 이다.

array([0])

In [19]:
irisData['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [20]:
print(f"예측:{prediction}")
print(f"예측 품종의 이름: {irisData['target_names'][prediction]}")

예측:[0]
예측 품종의 이름: ['setosa']


In [21]:
y_predict = knn.predict(X_test)
y_predict   # X _ test의 예측값..< 이 값을 y_ test와[레이블] 비교해본다> 

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2])

In [22]:
# 정확도를 계산하기 위해서 
# 1) numpy 의 mean() 메서드 이용  [또는] 
# 2 ) knn객체의 score() 메서드를 사용해도 된다 

# numyp mean() 메서드 이용 >> np.mean(y_predict == y_test) # 정확도가 약 97% 

In [23]:
# knn score() 메서드 이용     
knn.score(X_test, y_test)

0.9736842105263158

In [ ]:
# 좋은 퍼포먼스를 나태나기위해서는 좋은데이터를많이 모델에 훈련시켜야 함

In [ ]:
""" 정리 
1.iris 분류 문제 있어서 각품종을 클래스 라고 한다
2. 개별 iris품종은레이블이라고한다
3. 하나는데이터, 다른하나는 출력을 가지고 있다 
4.scikit-learn에서는 데이터는 X 로 표기하고, 출력은 y로 표기한다
5 .이 때 배열 X는 2차원 배열이고, 각행은 샘플에 해당한다
6. 각 컬럼은 (열) 은 특성!! 
7. 배열 y는 1차원 배열이고, 각 샘플의 클래스 레이블 


In [ ]:
# SUM (support Vector Mahine) >> 분류에서 사용하고 있는 알고리즘 (Hyper-plane을 이용하여)
