In [1]:
# 빅데이터 >> 데이터 보관/처리법  & 데이터 분석 방법들 
# 인공지능 >> 프로그램이 인간처럼 생각/행동하게 하는 학문 
# 머신러닝 >> 인공지능을 실현하는 기법 중 하나 
# 딥러닝 >> 머신러닝 기법 중 하나 ( 신경망을 이용하는!! ) 

In [2]:
# 머신러닝 
1) 지도 학습 >> 답이 있고 답을 맞추는게 학습의 목적 (문제와 답을 알려줌)
1-1) 분류 (Classfication) >> 스팸 또는 일반 메일 분류
1-2) 회귀  (Regression) >> 아파트 가격 예측

2) 비지도 학습 >> 답이 없고 답을맞추는게 학습의 목적 

3) 강화 학습

SyntaxError: unmatched ')' (<ipython-input-2-d802566a2b05>, line 2)

In [3]:
# numpy 로 행렬 만들기

In [4]:
import numpy as np 
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [5]:
A = np.array([[1,1,1],[3,2,4],[4,5,1],[3,7,6]])   
A   # 4 X 3 matrix 


array([[1, 1, 1],
       [3, 2, 4],
       [4, 5, 1],
       [3, 7, 6]])

In [6]:
B = np.array([[1,1],[2,3],[2,-1]])
B

array([[ 1,  1],
       [ 2,  3],
       [ 2, -1]])

In [7]:
C = np.random.rand(3,5)
C

array([[0.77430341, 0.99711039, 0.84204054, 0.77255701, 0.0127184 ],
       [0.1224163 , 0.59079652, 0.71406056, 0.32834198, 0.63866478],
       [0.66433847, 0.12894129, 0.59611689, 0.13627356, 0.97584113]])

In [8]:
D = np.zeros((2,4))
D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
A

array([[1, 1, 1],
       [3, 2, 4],
       [4, 5, 1],
       [3, 7, 6]])

In [10]:
A[0][2]

1

In [11]:
## 행렬을 만들어보자 

AA = np.array([[0,1,-1],[1,2,3],[2,1,0],[-1,2,-4]])
AA

array([[ 0,  1, -1],
       [ 1,  2,  3],
       [ 2,  1,  0],
       [-1,  2, -4]])

In [12]:
BB = np.array([[0,2],[1,1],[-1,-2]])
BB

array([[ 0,  2],
       [ 1,  1],
       [-1, -2]])

In [13]:
AA[1][1]  # 2행 2열 

2

In [14]:
AA[3][0]  # 4행1열 

-1

In [15]:
5 * A

array([[ 5,  5,  5],
       [15, 10, 20],
       [20, 25,  5],
       [15, 35, 30]])

In [16]:
# 행렬 연산 

A = np.array([[1,-1,2],[3,2,2]])
B = np.array([[0,1],[-1,1],[5,2]])
C = np.array([[2,-1],[3,-3]])
D = np.array([[-5,-1],[2,0]])



In [17]:
# 숫자/행렬 스칼라 곱은 *  ///  행렬 덧셈은 + /// 행렬 곱셈은 @ 
result = 2*A @ -B @ (3*C + D)
result

array([[-110,  160],
       [-214,  226]])

In [18]:
# tranoposed matrix >> 열, 행 을 바꾼거 
# indentity matrix >>  대각선의 요소가 1 
# 역행렬 >> 기존의 행렬과 곱하면은 identity matrix 가 나옴 

In [19]:
A_transpose = A.T 
A_transpose

array([[ 1,  3],
       [-1,  2],
       [ 2,  2]])

In [20]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
A_inverse = np.linalg.pinv(A)
A_inverse 

array([[ 0.02597403,  0.16883117],
       [-0.35064935,  0.22077922],
       [ 0.31168831,  0.02597403]])

In [22]:
A_inverse @ A

array([[ 0.53246753,  0.31168831,  0.38961039],
       [ 0.31168831,  0.79220779, -0.25974026],
       [ 0.38961039, -0.25974026,  0.67532468]])

In [23]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2]
])

B = np.array([
    [0, 1],
    [-1, 1],
    [5, 2]
])

C = np.array([
    [2, -1],
    [-3, 3]
])

D = np.array([
    [-5, 1],
    [2, 0]
])


In [24]:
C_inverse = np.linalg.pinv(C)
C_inverse

array([[1.        , 0.33333333],
       [1.        , 0.66666667]])

In [25]:
B.T @ (2*A.T) @ (3 * C + D.T )

array([[-106,  122],
       [-136,  154]])

In [26]:
# Why do we need linear alebra ??
""" B/C 머신러닝을 할 때는 데이터를 일차식에 사용하는 경우가 많다 
 행렬을 이요하면 정돈되 형태로 효율적이게 계산을 할 수 있다 
 선형 대수학은 일차식, 일차함수, 행렬, 벡터를 다루기 학문 """

' B/C 머신러닝을 할 때는 데이터를 일차식에 사용하는 경우가 많다 \n 행렬을 이요하면 정돈되 형태로 효율적이게 계산을 할 수 있다 \n 선형 대수학은 일차식, 일차함수, 행렬, 벡터를 다루기 학문 '

In [27]:
# 머신러닝에서 미분이 필요한 이유?!
""" 그래프의 최소점(성능최대화) 에서 머신 러닝이 가장 잘 구현되기 때문에"""

' 그래프의 최소점(성능최대화) 에서 머신 러닝이 가장 잘 구현되기 때문에'

In [28]:
# 선형회귀 (liner Regression) >> 지도 학습 중, [ 분류, 회귀 중 회귀를 뜻한다]
# 그리고 MSE ( Mean square error) 를 통해 검증한다
# MSE 평균 제곱 오차가 크면 ??  >> 가설 함수가 데이터에 잘 안 맞다 
# MSE 평균 제곱 오차가 작으면?? >> 가설 함수가 데이터에 잘 맞다 
""" 손실함수( Loss Function) 
* 가설 함수의 성능을 평가하는 함수 
* 손실 함수가 작으면? >> 가설 함수가 데이터에 잘 맞다 
* 손실 함수가 크면? >> 가설 함수가 데이터에 잘 안 맞다 """  


""" 목적? 
* 데이터에 가장 잘 맞는 가설 함수를 찾아야 함 
* h0(x) = A0 + A1x (가설함수)"""

' 목적? \n* 데이터에 가장 잘 맞는 가설 함수를 찾아야 함 \n* h0(x) = A0 + A1x (가설함수)'

In [29]:
# 선형 회귀 가설 함수 구현하기 

import numpy as np 

def prediction(theta_0, theta_1, x):
    return theta_0 + theta_1 * x 
    

house_size = np.array([0.9, 1.4, 2, 2.1, 2.6, 3.3, 3.35, 3.9, 4.4, 4.7, 5.2, 5.75, 6.7, 6.9])
theta_0 = -3
theta_1 = 2

prediction(theta_0, theta_1, house_size)

array([-1.2, -0.2,  1. ,  1.2,  2.2,  3.6,  3.7,  4.8,  5.8,  6.4,  7.4,
        8.5, 10.4, 10.8])

In [30]:
# 선형 회귀 예측 오차 구현하기 

import numpy as np 

def prediction(theta_0, theta_1, x):
    return theta_0 + theta_1 * x
    
def prediction_difference(theta_0, theta_1, x, y):   
    return prediction(theta_0, theta_1, x) - y 

house_size = np.array([0.9, 1.4, 2, 2.1, 2.6, 3.3, 3.35, 3.9, 4.4, 4.7, 5.2, 5.75, 6.7, 6.9])
house_price = np.array([0.3, 0.75, 0.45, 1.1, 1.45, 0.9, 1.8, 0.9, 1.5, 2.2, 1.75, 2.3, 2.49, 2.6])

theta_0 = -3
theta_1 = 2

prediction_difference(-3, 2, house_size, house_price)

array([-1.5 , -0.95,  0.55,  0.1 ,  0.75,  2.7 ,  1.9 ,  3.9 ,  4.3 ,
        4.2 ,  5.65,  6.2 ,  7.91,  8.2 ])

In [31]:
# 선형 회괴 경사 하강법 구하기 

import numpy as np

def prediction(theta_0, theta_1, x):
    """주어진 학습 데이터 벡터 x에 대해서 모든 예측 값을 벡터로 리턴하는 함수"""
    return theta_0 + theta_1 * x
    
    
def prediction_difference(theta_0, theta_1, x, y):
    """모든 예측 값들과 목표 변수들의 오차를 벡터로 리턴해주는 함수"""
    return prediction(theta_0, theta_1, x) - y

    
def gradient_descent(theta_0, theta_1, x, y, iterations, alpha):
    """주어진 theta_0, theta_1 변수들을 경사 하강를 하면서 업데이트 해주는 함수"""
    for _ in range(iterations):  # 정해진 번만큼 경사 하강을 한다
        error = prediction_difference(theta_0, theta_1, x, y)  # 예측값들과 입력 변수들의 오차를 계산
        # 코드를 쓰세요
        theta_0 = theta_0 - alpha * error.mean()
        theta_1 = theta_1 - alpha * (error * x).mean()
        
    return theta_0, theta_1
    

In [32]:
# 입력변수 (크기)

house_size = np.array([0.9, 1.4, 2, 2.1, 2.6, 3.3, 3.35, 3.9, 4.4, 4.7, 5.2, 5.75, 6.7, 6.9])
house_price = np.array([0.3, 0.75, 0.45, 1.1, 1.45, 0.9, 1.8, 0.9, 1.5, 2.2, 1.75, 2.3, 2.49, 2.6])
theta_0 = 2.5
theta_1 = 0

In [33]:
theta_0, theta_1 = gradient_descent(theta_0, theta_1, house_size, house_price, 200, 0.1)
theta_0, theta_1 

(0.16821801417752186, 0.3438032402351199)

In [34]:
# 모델 학습시키기 

Training Set vs Test Set 

>> 모든 데이터를 Training 을 하면은, 모델에 맞게 training 시켰기 때문에 신뢰도가 낮음 . 따라서 training, test 로 나누어서 함 


SyntaxError: invalid syntax (<ipython-input-34-bbe034286565>, line 3)

In [35]:
# 모델평가하기

"RMSE" (root mean square error)

>> 모델을 학습시키고 나서는 이 모델이 얼마나 좋은지 평가를 해야 함. 즉, 이 모델이 결과를 얼마나 정확히 예측하는지 평가 


SyntaxError: invalid syntax (<ipython-input-35-4536d5a52a80>, line 3)

In [36]:
# scikit - learn  ( 머신러닝 library) 

from sklearn.datasets import load_boston 
boston_data = load_boston()
print(boston_data.DESCR)  # description 

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [37]:
boston_data.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [38]:
boston_data.data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [39]:
boston_data.data.shape  # 506개의 데이터에 13 개 속성

(506, 13)

In [40]:
boston_data.target  # 목표변수 

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [41]:
boston_data.target.shape

(506,)

In [42]:
x = pd.DataFrame(boston_data.data, columns = boston_data.feature_names)
x

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [43]:
x = x[["AGE"]]
x

AGE
0    65.2
1    78.9
2    61.1
3    45.8
4    54.2
..    ...
501  69.1
502  76.7
503  91.0
504  89.3
505  80.8

[506 rows x 1 columns]

In [44]:
y = pd.DataFrame(boston_data.target, columns = ["MEDV"])
y

MEDV
0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
..    ...
501  22.4
502  20.6
503  23.9
504  22.0
505  11.9

[506 rows x 1 columns]

In [45]:
# training, test 셋으로 나누자 

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state =5)

In [46]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

# test, training (2:8)

(404, 1)
(102, 1)
(404, 1)
(102, 1)


In [47]:
model = LinearRegression()

In [48]:
model.fit(x_train, y_train)  # 

LinearRegression()

In [49]:
model.coef_

array([[-0.12402883]])

In [50]:
model.intercept_

array([31.04617413])

In [51]:
# 위의 최적선, f(x) = 31.04617413 - -0.12402883x  >> training set으로 훈련시킨 linerear regression model 

In [52]:
# 이제 test set 에 적용을 시켜보자!! 
y_test_prediction = model.predict(x_test)
y_test_prediction  # 예측값

array([[20.31768041],
       [28.14389953],
       [22.84786852],
       [18.64329122],
       [24.62148078],
       [19.99520545],
       [19.75955068],
       [22.79825699],
       [20.92542167],
       [21.74401194],
       [23.29437231],
       [25.41526529],
       [21.53316293],
       [25.94858925],
       [23.76568186],
       [24.55946636],
       [18.64329122],
       [18.64329122],
       [22.00447248],
       [18.64329122],
       [18.89134887],
       [18.90375176],
       [21.33471681],
       [22.71143681],
       [28.46637448],
       [19.06498923],
       [24.31140871],
       [22.05408402],
       [26.32067574],
       [26.59353916],
       [19.0153777 ],
       [18.85414022],
       [19.30064401],
       [18.7301114 ],
       [28.76404367],
       [18.92855752],
       [21.5579687 ],
       [19.21382383],
       [19.69753626],
       [29.08651863],
       [19.56110455],
       [18.64329122],
       [21.02464473],
       [20.14404005],
       [24.72070384],
       [25

In [53]:
mean_squared_error(y_test, y_test_prediction)**0.5  # y의 실제 값이랑 예측값을 비교 
## 8000 달러의 오차가 있음..

8.236881612652455

In [54]:
# 범죄율로 집 값 예측하기 
from sklearn import datasets 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import pandas as pd 


In [59]:
# 보스턴데이터 불러오기
Bdata = datasets.load_boston()
x = pd.DataFrame(Bdata.data, columns = Bdata.feature_names)  # 입력변수 
x

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [60]:
y = pd.DataFrame(Bdata.target, columns = ["MEDV"])
y

MEDV
0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
..    ...
501  22.4
502  20.6
503  23.9
504  22.0
505  11.9

[506 rows x 1 columns]

In [61]:
# step 1 >> 범죄율 열을 선택하기  (input 데이터)
x = x[["CRIM"]]
x

CRIM
0    0.00632
1    0.02731
2    0.02729
3    0.03237
4    0.06905
..       ...
501  0.06263
502  0.04527
503  0.06076
504  0.10959
505  0.04741

[506 rows x 1 columns]

In [65]:
# step 2 >> train, test 나누기 

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=5)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)
# train 과 test 비율은 4:! 
                                        
                                                   

(404, 1)
(102, 1)
(404, 1)
(102, 1)


In [68]:
# 모델 학습
model = LinearRegression()

model.fit(x_train, y_train)
print(model.intercept_)
print(model.coef_)

# training 을 훈련시킨 결과 f(X) = 24.122  -0.415X 


[24.12202188]
[[-0.41546547]]


In [69]:
# test셋어 적용시키자 

y_prediction = model.predict(x_test)
y_prediction

array([[23.96325591],
       [24.1070028 ],
       [24.10256148],
       [19.50698991],
       [24.0298384 ],
       [13.34459834],
       [24.0967782 ],
       [23.93593074],
       [24.08012634],
       [22.63935857],
       [24.09352095],
       [24.09918374],
       [23.97685825],
       [24.09910896],
       [24.07440954],
       [24.0964209 ],
       [16.30670095],
       [23.50035259],
       [24.00170308],
       [ 2.87686277],
       [24.03582941],
       [23.87687648],
       [23.99101315],
       [23.95499645],
       [24.11825776],
       [18.80310831],
       [24.04657751],
       [24.06735493],
       [24.10090377],
       [24.08899238],
       [24.05954418],
       [24.04583798],
       [18.57148631],
       [20.6952253 ],
       [24.08352485],
       [23.6263965 ],
       [23.90573887],
       [17.53261491],
       [23.90592167],
       [24.10806639],
       [20.53042262],
       [23.4453782 ],
       [23.86663526],
       [22.18228424],
       [24.09970308],
       [24

In [70]:
# 오차를 구해보자 MSE 
MSE = mean_squared_error(y_test, y_prediction)
MSE ** 0.5

8.180697228317348